name: 'Hacklet'

on:
  push:
    paths:
    - 'hacklet/**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --amd64 \
          --target hacklet \
          --image homeassistant-amd64-hacklet \
          --docker-hub ghcr.io/mcolyer
