name: 'Honeywell Sensors'

on:
  push:
    paths:
    - 'honeywell-sensors/**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --amd64 \
          --target honeywell-sensors \
          --image homeassistant-amd64-honeywell-sensors
          --docker-hub ghcr.io/mcolyer
