name: 'Voltlet'

on:
  push:
    paths:
    - 'voltlet/**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --amd64 \
          --target voltlet \
          --docker-hub ghcr.io/mcolyer
